// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu5wSrYFz2SJgah2cb_1Pbm8zFiN-1LAg',
    appId: '1:982308174016:web:88b7e9a5ddb18687299525',
    messagingSenderId: '982308174016',
    projectId: 'navaflutter',
    authDomain: 'navaflutter.firebaseapp.com',
    storageBucket: 'navaflutter.appspot.com',
    measurementId: 'G-MQZXWKT9ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfqiURdwa28A-Yby_et-OQ8cZG3UyJR5g',
    appId: '1:982308174016:android:004e37a1c60c620f299525',
    messagingSenderId: '982308174016',
    projectId: 'navaflutter',
    storageBucket: 'navaflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyrzQ97SPSvyRUJiu1Pc6oUWRzFWl87aQ',
    appId: '1:982308174016:ios:70ba03425883fb98299525',
    messagingSenderId: '982308174016',
    projectId: 'navaflutter',
    storageBucket: 'navaflutter.appspot.com',
    iosClientId: '982308174016-f6eath10pjvj0ohld81p0v7qatj5bd1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.navaFlutter',
  );
}
